- name: Working with JunOS NETCONF
  hosts: all
  connection: netconf
  gather_facts: no

  tasks:
    - name: Include vars
      include_vars:
        dir: vars

    - name: Generate configs
      template:
        src: vRR.j2
        dest: configs/{{ hostname }}.cfg
      tags: gen

    - name: Configure devices
      netconf_config:
        src: configs/{{ hostname }}.cfg
      tags: deploy
