- name: Handle CE routers
  hosts: CE
  connection: netconf
  gather_facts: no
  become: yes
  become_method: enable

  roles:
    - CE

- name: Handle PE routers
  hosts: PE
  connection: netconf
  gather_facts: no
  become: yes
  become_method: enable

  roles:
    - PE

- name: Handle P routers
  hosts: P
  connection: netconf
  gather_facts: no
  become: yes
  become_method: enable

  roles:
    - P
