version: "2"

services:
  influx:
    image: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: mdt_db
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
