- name: Run show commands on routers
  hosts: all
  connection: network_cli
  gather_facts: no
  become: yes
  become_method: enable

  tasks:
    - name: Show arp
      ios_command:
        commands: sh ip arp
      register: arp

    - name: Print result
      debug: var=arp.stdout_lines
