- name: Include vars
  include_vars:
    dir: vars

- name: Generate configs
  template:
    src: RR.j2
    dest: "roles/fvrr/files/{{ hostname }}.cfg"

- name: Configure devices
  netconf_config:
    src: "roles/fvrr/files/{{ hostname }}.cfg"
