policy_statements:
  CGW_IMPORT:
    ALLOW_V4:
      from:
        community:
          - YC_NET_AGG
        route-filters:
          - address: 130.193.32.0/19
            prefix_length_range: /24-/24
      then:
        action: accept
    ALLOW_test_NET:
      from:
        community:
          - YC_NET_AGG
        route-filters:
          - address: 130.193.47.0/24
            prefix_length_range: /24-/32
      then:
        action: accept
    DEFAULT_REJECT:
      then:
        action: reject
  FV_IMPORT:
    DENY_BORDERS:
      from:
        prefix-lists-filters:
          - name: BORDERS
            option: exact
      then:
        action: reject
    ALLOW:
      from:
        community:
          - EUROPE
          - USA
          - TRANSIT
          - YANDEX_MONEY
      then:
        metric: 0
        communities:
          - action: delete
            name: WILD
        action: accept
    DEFAULT_REJECT:
      then:
        action: reject
  LU_EXPORT:
    LO:
      from:
        interface:
          - lo0.0
      then:
        communities:
          - action: add
            name: GEO_DC
          - action: add
            name: GEO_MODULE
          - action: add
            name: YC
          - action: add
            name: CLOUD_FV_RR_LO
          - action: add
            name: CLOUD_RKUB_RR_LO
          - action: add
            name: CLOUD_SLB_RR_LO
        action: accept
    DEFAULT_REJECT:
      then:
        action: reject
  LU_IMPORT:
    NO_ADVERTISE:
      then:
        communities:
          - action: add
            name: NO_ADVERTISE
  NO_EXPORT:
    NO_EXPORT:
      then:
        action: reject
  RKUB_IMPORT:
    ALLOW:
      from:
        community:
          - RKUB
      then:
        local-preference: 400
        action: accept
    DEFAULT_REJECT:
      then:
        action: reject
  SLB_EXPORT:
    ALLOW:
      from:
        community:
          - YC_NET_AGG
      then:
        communities:
          - action: add
            name: FW_COMMUNITY
          - action: add
            name: YC
        action: accept
    DEFAULT_REJECT:
      then:
        action: reject
  SLB_IMPORT:
    DENY_BORDERS:
      from:
        prefix-lists-filters:
          - name: BORDERS
            option: exact
      then:
        action: reject
