routing_instances:
  MGMT:
    instance_type: vrf
    interfaces:
      - em1.0
    rd: 37.140.141.81:1
    rt: target:1:1
    routing_options:
      ribs:
        MGMT.inet6.0:
          static_routes:
            ::/0:
              nexthop: 2a02:6b8:bf00:1002::1
              metric: 20
