- name: Run show commands on routers
  hosts: all
  connection: network_cli
  gather_facts: no
  become: yes
  become_method: enable

  tasks:
    - name: Generate configs
      template:
        src: base.j2
        dest: configs/{{ hostname }}.cfg
      tags: gen

    - name: Configure devices
      ios_config:
        src: configs/{{ hostname }}.cfg
      tags: deploy
