# - hosts: 192.168.0.95
#   become: yes

#   tasks:
#   - name: Deploy vRR
#     tags: deploy
#     import_role:
#       name: kvm
#     vars:
#       operation: deploy

#   - name: Undeploy vRR
#     tags: undeploy
#     import_role:
#       name: kvm
#     vars:
#       operation: undeploy

- hosts: 192.168.0.111
  connection: netconf

  tasks:
  - name: Configure vRR
    tags: deploy
    import_role:
      name: vrr
    vars:
      ansible_ssh_user: root
      ansible_ssh_pass: Juniper
      operation: deploy
