all:
  vars:
    ansible_network_os: ios
    users:
      - name: admin
        pass: admin
      - name: cisco1
        pass: cisco1
      - name: cisco2
        pass: cisco2
  children:
    PE:
      hosts:
        192.168.0.203:
        192.168.0.204:
    P:
      hosts:
        192.168.0.205:
    CE:
      hosts:
        192.168.0.201:
        192.168.0.202:
