---

- name: Concifure L3 interface on NX
  hosts: nx
  connection: local

  tasks:

    - name: configure ethernet1/1 interface
      nxos_interface:
        interface: ethernet1/1
        admin_state: up
        mode: layer3
        description: "Configured with Ansible"
        state: present
        provider: "{{ cli }}"

    - name: configure ethernet1/1 ip address
      nxos_ip_interface:
        interface: ethernet1/1
        addr: "10.0.0.1"
        mask: 30
        state: present
        provider: "{{ cli }}"
