- name: Destroy VM
  virt:
    name: "{{ hostname }}"
    command: destroy
  ignore_errors: yes

- name: Undefine VM
  virt:
    name: "{{ hostname }}"
    command: undefine
  ignore_errors: yes

- name: Delete VM image
  file:
    path: "/var/lib/libvirt/images/{{ hostname }}.img"
    state: absent
