- name: Install packages
  apt:
    name: [qemu-kvm, libvirt-bin, ubuntu-vm-builder, bridge-utils]
    update_cache: yes

- name: Copy vRR image
  copy:
    src: ~/junos-x86-64-16.2R2-S3.img
    dest: /var/lib/libvirt/images/ansible_vrr.img

- name: Define VM
  virt:
    name: ansible_vrr
    command: define
    xml: "{{ lookup('template', 'templates/kvm.j2') }}"

- name: Launch VM
  virt:
    name: ansible_vrr
    state: running

- name: Waiting for VM to boot
  pause:
    seconds: 450

- name: Copy magic_wand script to host
  copy:
    src: magic_wand2.py
    dest: "/home/{{ lookup('env', 'USER') }}/"
  become: no

- name: Making router reachable via CLI
  command: python "/home/{{ lookup('env', 'USER') }}/magic_wand2.py"

# - name: Making router reachable via CLI
#   script: magic_wand.py
#   become: no

# - name: Configure management interface via telnet
#   telnet:
#     port: 3517
#     user: root
#     pause: 1
#     login_prompt: 'login: '
#     prompts:
#       - "[>|#]"
#     command:
#       - cli
#       - edit
#       - set system services ssh
#       - set system root-authentication plain-text-password
#       - Juniper
#       - Juniper
#       - set system services netconf rfc-compliant ssh port 830
#       - set interface em0 unit 0 family inet address 192.168.0.111/24
#       - commit
